[build]
command = "yarn build"
publish = "dist"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/server.js"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/.netlify/functions/server.js"
status = 200
force = true
